<?php

/**
 * @file
 * This is superinfo module.
 */

use Drupal\Core\Form\FormStateInterface;

use Drupal\superinfo\FormAlter\NodeFormAlter;

/**
 * Implements hook_form_alter().
 */
function superinfo_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'node_repair_form') {
    $NodeFormAlter = new NodeFormAlter();
    $NodeFormAlter->nodeRepairFormAlter($form);
  }
  elseif ($form_id == 'node_quote_form') {
    $NodeFormAlter = new NodeFormAlter();
    $NodeFormAlter->nodeQuoteFormAlter($form);
  }

}
